# -*- coding: utf-8 -*-
"""
Rich Product Catalog with multi-currency pricing, dietary tags, stock status, and clean icons.
"""

PRODUCTS = [
    # Dairy & Eggs
    {
        'id': 'prod_001',
        'key': 'milk',
        'name': 'Fresh Farm Whole Milk',
        'brand': 'Amul / Organic Valley',
        'category': 'Dairy & Eggs',
        'price_inr': 66.0,
        'price_usd': 1.80,
        'unit': 'liter',
        'dietary': ['Vegetarian', 'Gluten-Free', 'High Calcium'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🥛',
        'image': 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&q=80',
        'calories': '146 kcal / cup',
        'description': 'Pure farm-fresh pasteurized whole milk, rich in calcium and vitamin D.'
    },
    {
        'id': 'prod_002',
        'key': 'egg',
        'name': 'Farm Fresh Brown Eggs (Pack of 6)',
        'brand': 'Eggoz / Vital Farms',
        'category': 'Dairy & Eggs',
        'price_inr': 55.0,
        'price_usd': 1.50,
        'unit': 'packet',
        'dietary': ['Non-Vegetarian', 'High Protein', 'Keto'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🥚',
        'image': 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=300&q=80',
        'calories': '72 kcal / egg',
        'description': 'Free-range pasture-raised brown eggs with rich golden yolks.'
    },
    {
        'id': 'prod_003',
        'key': 'butter',
        'name': 'Pasteurized Salted Butter',
        'brand': 'Amul Butter',
        'category': 'Dairy & Eggs',
        'price_inr': 58.0,
        'price_usd': 1.40,
        'unit': 'packet',
        'dietary': ['Vegetarian', 'Keto'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🧈',
        'image': 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=300&q=80',
        'calories': '102 kcal / tbsp',
        'description': 'Creamy, rich golden butter crafted from fresh cow milk cream.'
    },
    {
        'id': 'prod_004',
        'key': 'cheese',
        'name': 'Fresh Malai Paneer / Cottage Cheese',
        'brand': 'Mother Dairy / Kraft',
        'category': 'Dairy & Eggs',
        'price_inr': 90.0,
        'price_usd': 2.20,
        'unit': 'packet',
        'dietary': ['Vegetarian', 'High Protein', 'Gluten-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.7,
        'emoji': '🧀',
        'image': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300&q=80',
        'calories': '265 kcal / 100g',
        'description': 'Soft and succulent premium paneer blocks, ideal for curries and grilling.'
    },
    {
        'id': 'prod_005',
        'key': 'yogurt',
        'name': 'Probiotic Greek Curd / Dahi',
        'brand': 'Epigamia',
        'category': 'Dairy & Eggs',
        'price_inr': 45.0,
        'price_usd': 1.10,
        'unit': 'box',
        'dietary': ['Vegetarian', 'Probiotic', 'Low Fat'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🥣',
        'image': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300&q=80',
        'calories': '97 kcal / 100g',
        'description': 'Thick, creamy set curd with live active gut-friendly probiotics.'
    },

    # Fresh Produce - Fruits
    {
        'id': 'prod_006',
        'key': 'apple',
        'name': 'Crisp Royal Gala Apples',
        'brand': 'Kashmir Orchards / Washington',
        'category': 'Fresh Fruits',
        'price_inr': 140.0,
        'price_usd': 3.20,
        'unit': 'kg',
        'dietary': ['Vegan', 'Organic', 'Fiber Rich'],
        'season': 'Winter & All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🍎',
        'image': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&q=80',
        'calories': '95 kcal / apple',
        'description': 'Juicy, sweet and crisp mountain-harvested premium Royal Gala apples.'
    },
    {
        'id': 'prod_007',
        'key': 'banana',
        'name': 'Golden Cavendish Bananas (Robusta)',
        'brand': 'Kerala Harvest / Chiquita',
        'category': 'Fresh Fruits',
        'price_inr': 50.0,
        'price_usd': 1.20,
        'unit': 'dozen',
        'dietary': ['Vegan', 'Energy Booster', 'Potassium Rich'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🍌',
        'image': 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=300&q=80',
        'calories': '105 kcal / banana',
        'description': 'Naturally ripened nutrient-rich bananas, perfect breakfast fruit.'
    },
    {
        'id': 'prod_008',
        'key': 'orange',
        'name': 'Sweet Nagpur Oranges',
        'brand': 'Nagpur Fresh',
        'category': 'Fresh Fruits',
        'price_inr': 80.0,
        'price_usd': 2.00,
        'unit': 'kg',
        'dietary': ['Vegan', 'Vitamin C', 'Immunity'],
        'season': 'Winter',
        'stock': 'In Stock',
        'rating': 4.6,
        'emoji': '🍊',
        'image': 'https://images.unsplash.com/photo-1547514701-42782101795e?w=300&q=80',
        'calories': '62 kcal / orange',
        'description': 'Refreshing citrus burst loaded with natural Vitamin C.'
    },

    # Fresh Produce - Vegetables
    {
        'id': 'prod_009',
        'key': 'potato',
        'name': 'Fresh Hill Potatoes (Aaloo)',
        'brand': 'Agra Farms',
        'category': 'Fresh Vegetables',
        'price_inr': 35.0,
        'price_usd': 0.90,
        'unit': 'kg',
        'dietary': ['Vegan', 'Gluten-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.7,
        'emoji': '🥔',
        'image': 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&q=80',
        'calories': '77 kcal / 100g',
        'description': 'Firm, unblemished cooking potatoes for curries, bakes, and fries.'
    },
    {
        'id': 'prod_010',
        'key': 'tomato',
        'name': 'Ripe Hybrid Red Tomatoes (Tamatar)',
        'brand': 'Local Farm Fresh',
        'category': 'Fresh Vegetables',
        'price_inr': 40.0,
        'price_usd': 1.00,
        'unit': 'kg',
        'dietary': ['Vegan', 'Lycopene Rich', 'Organic'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🍅',
        'image': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&q=80',
        'calories': '18 kcal / 100g',
        'description': 'Plump, tangy red tomatoes packed with antioxidants and vitamin C.'
    },
    {
        'id': 'prod_011',
        'key': 'onion',
        'name': 'Fresh Nasik Red Onions (Pyaaz)',
        'brand': 'Nasik Harvest',
        'category': 'Fresh Vegetables',
        'price_inr': 45.0,
        'price_usd': 1.10,
        'unit': 'kg',
        'dietary': ['Vegan', 'Gluten-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.7,
        'emoji': '🧅',
        'image': 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=300&q=80',
        'calories': '40 kcal / 100g',
        'description': 'Pungent, flavourful red onions essential for every kitchen base.'
    },
    {
        'id': 'prod_012',
        'key': 'ginger',
        'name': 'Fresh Ginger Root (Adrak / Inji)',
        'brand': 'Wayanad Organic',
        'category': 'Fresh Vegetables',
        'price_inr': 60.0,
        'price_usd': 1.50,
        'unit': 'gram',
        'dietary': ['Vegan', 'Immunity Booster', 'Digestive'],
        'season': 'Monsoon & Winter',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🫚',
        'image': 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=300&q=80',
        'calories': '80 kcal / 100g',
        'description': 'Aromatic, spicy ginger root for chai, marinades, and stir-fries.'
    },
    {
        'id': 'prod_013',
        'key': 'garlic',
        'name': 'Organic Garlic Bulbs (Lehsun)',
        'brand': 'Organic Tattva',
        'category': 'Fresh Vegetables',
        'price_inr': 70.0,
        'price_usd': 1.80,
        'unit': 'gram',
        'dietary': ['Vegan', 'Heart Health', 'Antimicrobial'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🧄',
        'image': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=300&q=80',
        'calories': '149 kcal / 100g',
        'description': 'Richly aromatic garlic cloves that elevate curries and pasta sauces.'
    },
    {
        'id': 'prod_014',
        'key': 'spinach',
        'name': 'Hydroponic Baby Spinach (Palak)',
        'brand': 'Green Farm',
        'category': 'Fresh Vegetables',
        'price_inr': 30.0,
        'price_usd': 0.80,
        'unit': 'packet',
        'dietary': ['Vegan', 'Iron Rich', 'Low Calorie'],
        'season': 'Winter & Monsoon',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🥬',
        'image': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300&q=80',
        'calories': '23 kcal / 100g',
        'description': 'Tender washed baby spinach leaves loaded with iron, folate, and vitamins.'
    },

    # Pantry & Staples
    {
        'id': 'prod_015',
        'key': 'rice',
        'name': 'Royal Aged Basmati Rice (Long Grain)',
        'brand': 'India Gate / Daawat',
        'category': 'Pantry & Staples',
        'price_inr': 125.0,
        'price_usd': 3.00,
        'unit': 'kg',
        'dietary': ['Vegan', 'Gluten-Free', 'Aromatic'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🍚',
        'image': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&q=80',
        'calories': '130 kcal / 100g cooked',
        'description': 'Aged 2 years for signature aroma and slender separate non-sticky grains.'
    },
    {
        'id': 'prod_016',
        'key': 'flour',
        'name': '100% Sharbati Whole Wheat Atta',
        'brand': 'Aashirvaad / Pillsbury',
        'category': 'Pantry & Staples',
        'price_inr': 60.0,
        'price_usd': 1.50,
        'unit': 'kg',
        'dietary': ['Vegetarian', 'High Fiber'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🌾',
        'image': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&q=80',
        'calories': '340 kcal / 100g',
        'description': 'Traditional stone-ground whole wheat flour for soft rotis and parathas.'
    },
    {
        'id': 'prod_017',
        'key': 'sugar',
        'name': 'Refined Sulfur-Free Sugar (Cheeni)',
        'brand': 'Madhur / Domino',
        'category': 'Pantry & Staples',
        'price_inr': 48.0,
        'price_usd': 1.10,
        'unit': 'kg',
        'dietary': ['Vegetarian', 'Gluten-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.6,
        'emoji': '🍬',
        'image': 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?w=300&q=80',
        'calories': '387 kcal / 100g',
        'description': 'Sparkling clean, untouched by hand, 100% sulfur-free crystal sugar.'
    },
    {
        'id': 'prod_018',
        'key': 'salt',
        'name': 'Vacuum Evaporated Iodized Salt (Namak)',
        'brand': 'Tata Salt / Morton',
        'category': 'Pantry & Staples',
        'price_inr': 28.0,
        'price_usd': 0.70,
        'unit': 'kg',
        'dietary': ['Vegan', 'Iodized'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🧂',
        'image': 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=300&q=80',
        'calories': '0 kcal',
        'description': 'Pure free-flowing iodized salt for everyday balanced health.'
    },
    {
        'id': 'prod_019',
        'key': 'dal',
        'name': 'Organic Unpolished Toor Dal (Arhar)',
        'brand': 'Tata Sampann',
        'category': 'Pantry & Staples',
        'price_inr': 145.0,
        'price_usd': 3.50,
        'unit': 'kg',
        'dietary': ['Vegan', 'High Protein', 'Gluten-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🍲',
        'image': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300&q=80',
        'calories': '343 kcal / 100g',
        'description': 'Unpolished yellow lentils retaining natural dietary fiber and plant protein.'
    },
    {
        'id': 'prod_020',
        'key': 'oil',
        'name': 'Cold-Pressed Sunflower Cooking Oil',
        'brand': 'Fortune / Bertolli',
        'category': 'Pantry & Staples',
        'price_inr': 160.0,
        'price_usd': 3.80,
        'unit': 'liter',
        'dietary': ['Vegan', 'Heart-Friendly', 'Vitamin E'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🌻',
        'image': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&q=80',
        'calories': '884 kcal / 100ml',
        'description': 'Light, high smoke point pure oil enriched with essential Omega-6.'
    },

    # Bakery & Breakfast
    {
        'id': 'prod_021',
        'key': 'bread',
        'name': '100% Whole Wheat Sandwich Bread',
        'brand': 'Modern / Wonder',
        'category': 'Bakery & Breakfast',
        'price_inr': 45.0,
        'price_usd': 1.10,
        'unit': 'packet',
        'dietary': ['Vegetarian', 'High Fiber', 'Zero Maida'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.7,
        'emoji': '🍞',
        'image': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&q=80',
        'calories': '70 kcal / slice',
        'description': 'Soft and wholesome whole grain bread baked fresh daily.'
    },
    {
        'id': 'prod_022',
        'key': 'honey',
        'name': '100% Pure Organic Forest Honey',
        'brand': 'Dabur / Nature Nates',
        'category': 'Bakery & Breakfast',
        'price_inr': 180.0,
        'price_usd': 4.20,
        'unit': 'bottle',
        'dietary': ['Vegetarian', 'Raw', 'Antioxidant'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🍯',
        'image': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=300&q=80',
        'calories': '64 kcal / tbsp',
        'description': 'Raw unprocessed honey with natural pollen and immunity enzymes.'
    },
    {
        'id': 'prod_023',
        'key': 'oats',
        'name': 'Whole Grain Rolled Oats',
        'brand': 'Quaker Oats',
        'category': 'Bakery & Breakfast',
        'price_inr': 95.0,
        'price_usd': 2.30,
        'unit': 'packet',
        'dietary': ['Vegan', 'Heart Health', 'Beta-Glucan'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🥣',
        'image': 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&q=80',
        'calories': '389 kcal / 100g',
        'description': '100% whole grain oats proven to help manage cholesterol.'
    },

    # Beverages
    {
        'id': 'prod_024',
        'key': 'tea',
        'name': 'Assam Gold CTC Leaf Tea (Chai)',
        'brand': 'Tata Tea Gold / Twinings',
        'category': 'Beverages',
        'price_inr': 150.0,
        'price_usd': 3.60,
        'unit': 'packet',
        'dietary': ['Vegan', 'Rich Aroma'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '☕',
        'image': 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&q=80',
        'calories': '2 kcal / cup',
        'description': 'Rich blend of Assam CTC and gently rolled long leaves for strong aroma.'
    },
    {
        'id': 'prod_025',
        'key': 'coffee',
        'name': 'Classic Instant Roast Coffee',
        'brand': 'Nescafé / Bru Gold',
        'category': 'Beverages',
        'price_inr': 190.0,
        'price_usd': 4.50,
        'unit': 'bottle',
        'dietary': ['Vegan', 'Caffeine Kick'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '☕',
        'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&q=80',
        'calories': '5 kcal / cup',
        'description': 'Finely roasted Arabica and Robusta beans for intense morning brew.'
    },
    {
        'id': 'prod_026',
        'key': 'water',
        'name': 'Packaged Natural Spring Mineral Water',
        'brand': 'Himalayan / Evian',
        'category': 'Beverages',
        'price_inr': 20.0,
        'price_usd': 0.60,
        'unit': 'liter',
        'dietary': ['Vegan', 'Electrolytes'],
        'season': 'Summer & All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '💧',
        'image': 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=300&q=80',
        'calories': '0 kcal',
        'description': 'Pure mountain water naturally enriched with essential ionic minerals.'
    },

    # Snacks & Personal Care
    {
        'id': 'prod_027',
        'key': 'biscuit',
        'name': 'Dark Chocolate Chip Cookies',
        'brand': 'Hide & Seek / Oreo',
        'category': 'Snacks & Treats',
        'price_inr': 40.0,
        'price_usd': 1.00,
        'unit': 'packet',
        'dietary': ['Vegetarian'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🍪',
        'image': 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300&q=80',
        'calories': '480 kcal / 100g',
        'description': 'Crunchy chocolate biscuits loaded with real chocolate chips.'
    },
    {
        'id': 'prod_028',
        'key': 'toothpaste',
        'name': 'Total Complete Gum Care Toothpaste',
        'brand': 'Colgate Total / Sensodyne',
        'category': 'Personal Care',
        'price_inr': 95.0,
        'price_usd': 2.30,
        'unit': 'packet',
        'dietary': ['Dental Safe'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.8,
        'emoji': '🪥',
        'image': 'https://images.unsplash.com/photo-1559591937-e1069f109fb3?w=300&q=80',
        'calories': 'N/A',
        'description': '12-hour antibacterial shield for teeth, gums, enamel, and fresh breath.'
    },
    {
        'id': 'prod_029',
        'key': 'soap',
        'name': 'Ayurvedic Neem & Aloe Vera Bathing Soap',
        'brand': 'Medimix / Dove',
        'category': 'Personal Care',
        'price_inr': 38.0,
        'price_usd': 0.90,
        'unit': 'piece',
        'dietary': ['Cruelty-Free'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.7,
        'emoji': '🧼',
        'image': 'https://images.unsplash.com/photo-1607006483702-34f40f09a8ec?w=300&q=80',
        'calories': 'N/A',
        'description': 'Gentle cleansing herbal soap enriched with 18 authentic herbs.'
    },
    {
        'id': 'prod_030',
        'key': 'almond',
        'name': 'Premium California Crunchy Almonds',
        'brand': 'Happilo / Blue Diamond',
        'category': 'Snacks & Treats',
        'price_inr': 240.0,
        'price_usd': 5.80,
        'unit': 'packet',
        'dietary': ['Vegan', 'Keto', 'Brain Health'],
        'season': 'All-Year',
        'stock': 'In Stock',
        'rating': 4.9,
        'emoji': '🥜',
        'image': 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=300&q=80',
        'calories': '579 kcal / 100g',
        'description': 'Hand-picked Californian raw almonds packed with healthy fats and Vitamin E.'
    }
]

def get_all_products():
    return PRODUCTS

def get_product_by_key(key):
    k = key.lower().strip()
    for p in PRODUCTS:
        if p['key'] == k or k in p['name'].lower():
            return p
    return None

def get_categories():
    cats = set(p['category'] for p in PRODUCTS)
    return sorted(list(cats))

def search_products(query="", category=None, max_price=None, currency='INR', dietary=None):
    results = PRODUCTS
    if category and category != "All Categories":
        results = [p for p in results if p['category'] == category]

    if max_price:
        if currency == 'USD':
            results = [p for p in results if p['price_usd'] <= max_price]
        else:
            results = [p for p in results if p['price_inr'] <= max_price]

    if dietary and dietary != "All":
        results = [p for p in results if any(dietary.lower() in d.lower() for d in p['dietary'])]

    if query and query.strip():
        q = query.lower().strip()
        results = [
            p for p in results
            if q in p['name'].lower() or q in p['key'].lower() or q in p['description'].lower() or q in p['brand'].lower()
        ]
    return results